templates:
  tabular_explainer: &tabular_explainer
    supported_data_types:
      - tabular

shap:
  <<: *tabular_explainer
  type: shap
  description: "Tree/Kernel SHAP with default background size."
  params:
    experiment:
      explanation:
        max_instances: 1
        sampling_strategy: random
        background_sample_size: 100

lime:
  <<: *tabular_explainer
  type: lime
  description: "LIME with 500 perturbations."
  params:
    experiment:
      explanation:
        max_instances: 1
        sampling_strategy: random
        lime_num_samples: 500
        lime_noise_scale: 0.1
        lime_kernel_width: 2.0

integrated_gradients:
  <<: *tabular_explainer
  type: integrated_gradients
  description: "Finite-difference IG."
  params:
    experiment:
      explanation:
        max_instances: 1
        sampling_strategy: random
        ig_steps: 30 # Sundararajan et al suggest that that somewhere between 20 and 300 steps are enough to approximate the integral (within 5%),.
        ig_epsilon: 0.001

causal_shap:
  <<: *tabular_explainer
  type: causal_shap
  description: "Causal SHAP with correlation threshold."
  params:
    experiment:
      explanation:
        max_instances: 1
        sampling_strategy: random
        causal_shap_corr_threshold: 0.3
        causal_shap_coalitions: 50
