templates:
  tabular_explainer: &tabular_explainer
    supported_data_types:
      - tabular

shap:
  <<: *tabular_explainer
  type: shap
  description: "Tree/Kernel SHAP with default background size."
  params:
    experiment:
      logging:
        level: WARNING
        library_level: WARNING
      explanation:
        max_instances: 100
        method_max_instances: 200
        sampling_strategy: random
        random_state: 42
        background_sample_size: 100

lime:
  <<: *tabular_explainer
  type: lime
  description: "LIME with 500 perturbations."
  params:
    experiment:
      explanation:
        max_instances: 100
        method_max_instances: 200
        sampling_strategy: random
        random_state: 42
        lime_num_samples: 100
        lime_noise_scale: 0.1
        lime_kernel_width: 2.0

integrated_gradients:
  <<: *tabular_explainer
  type: integrated_gradients
  description: "Finite-difference IG."
  params:
    experiment:
      explanation:
        max_instances: 100
        method_max_instances: 200
        sampling_strategy: random
        random_state: 42
        ig_steps: 40 # Sundararajan et al suggest that that somewhere between 20 and 300 steps are enough to approximate the integral (within 5%),.
        ig_epsilon: 1e-6

causal_shap:
  <<: *tabular_explainer
  type: causal_shap
  description: "Causal SHAP with correlation threshold."
  params:
    experiment:
      explanation:
        max_instances: 100
        method_max_instances: 200
        sampling_strategy: random
        random_state: 42
        causal_shap_corr_threshold: 0.3
        causal_shap_coalitions: 20
