settings:
  cv_folds: 5
  scoring: accuracy
  n_jobs: -1
  verbose: 2
  optimization_method: optuna
  n_trials: 100
  timeout: 3600

grids:
  decision_tree:
    max_depth: [3, 5, 7, 10, null]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    criterion: ['gini', 'entropy']
  random_forest:
    n_estimators: [50, 100, 200]
    max_depth: [5, 10, 15, null]
    min_samples_split: [2, 5, 10]
    max_features: ['sqrt', 'log2', null]
  gradient_boosting:
    n_estimators: [50, 100, 200]
    learning_rate: [0.01, 0.1, 0.2]
    max_depth: [3, 5, 7]
    min_samples_split: [2, 5, 10]
    subsample: [0.8, 0.9, 1.0]
  mlp: &mlp_defaults
    hidden_layer_sizes:
      - [50]
      - [100]
      - [50, 50]
      - [100, 50]
    activation: ['relu', 'tanh']
    alpha: [0.0001, 0.001, 0.01]
    max_iter: [500, 1000]
  mlp_classifier:
    <<: *mlp_defaults
